import type { Plan } from '@/types'

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Gratuito',
    price: 0,
    description: 'Comece sua jornada de bem-estar',
    color: '#9CA3AF',
    features: [
      '5 aulas por mês',
      'Biblioteca básica de pilates',
      'Diário de humor',
      'Comunidade básica',
      'App mobile',
    ],
  },
  {
    id: 'essential',
    name: 'Essencial',
    price: 39.90,
    yearlyPrice: 399.00,
    description: 'Ideal para quem está começando',
    color: '#52845A',
    features: [
      'Aulas ilimitadas',
      'Biblioteca completa de pilates',
      'Programas de 30 dias',
      'Acompanhamento de progresso',
      'Comunidade completa',
      'App mobile + PWA',
      'Suporte via email',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 79.90,
    yearlyPrice: 799.00,
    description: 'A experiência completa de wellness',
    color: '#A8744E',
    highlight: true,
    badge: 'Mais Popular',
    features: [
      'Tudo do Essencial',
      'Módulo de saúde mental',
      'Diário nutricional',
      'Gisele IA — personal trainer',
      'Aulas ao vivo semanais',
      'Planos personalizados',
      'Download offline',
      'Suporte prioritário',
    ],
  },
  {
    id: 'integral',
    name: 'Integral',
    price: 149.90,
    yearlyPrice: 1499.00,
    description: 'Saúde integrada completa',
    color: '#6B4E3D',
    features: [
      'Tudo do Premium',
      'Teleconsultas mensais',
      'Avaliação física digital',
      'Plano alimentar personalizado',
      'Suporte de psicóloga',
      'Análise corporal avançada',
      'Programas de 90 dias',
      'Suporte 24/7',
    ],
  },
  {
    id: 'concierge',
    name: 'Concierge',
    price: 399.90,
    yearlyPrice: 3999.00,
    description: 'Acompanhamento exclusivo e personalizado',
    color: '#1A0F0A',
    badge: 'Exclusivo',
    features: [
      'Tudo do Integral',
      'Sessões semanais 1:1 com Gisele',
      'Plano totalmente personalizado',
      'Acesso prioritário 24/7',
      'Equipe multidisciplinar dedicada',
      'Relatórios de saúde mensais',
      'Aulas privadas ao vivo',
      'Grupo VIP exclusivo',
    ],
  },
]

export const NAV_ITEMS = [
  { label: 'Pilates', href: '/pilates' },
  { label: 'Treinamento', href: '/training' },
  { label: 'Saúde Mental', href: '/mental' },
  { label: 'Nutrição', href: '/nutrition' },
  { label: 'Comunidade', href: '/community' },
  { label: 'Gisele IA', href: '/ai' },
]

export const DASHBOARD_NAV = [
  { label: 'Início',       href: '/dashboard',            icon: 'home' },
  { label: 'Minha Jornada',href: '/dashboard/journey',    icon: 'compass' },
  { label: 'Pilates',      href: '/dashboard/pilates',    icon: 'activity' },
  { label: 'Treinamento',  href: '/dashboard/training',   icon: 'dumbbell' },
  { label: 'Saúde Mental', href: '/dashboard/mental',     icon: 'brain' },
  { label: 'Nutrição',     href: '/dashboard/nutrition',  icon: 'apple' },
  { label: 'Consultas',    href: '/dashboard/appointments',icon: 'calendar' },
  { label: 'Comunidade',   href: '/dashboard/community',  icon: 'users' },
  { label: 'Gisele IA',    href: '/dashboard/ai',         icon: 'sparkles' },
  { label: 'Progresso',    href: '/dashboard/progress',   icon: 'trending-up' },
  { label: 'Perfil',       href: '/dashboard/profile',    icon: 'user' },
]

export const PILATES_CATEGORIES = [
  { id: 'beginner',     label: 'Iniciante',       color: '#52845A' },
  { id: 'intermediate', label: 'Intermediário',   color: '#A8744E' },
  { id: 'advanced',     label: 'Avançado',        color: '#6B4E3D' },
  { id: 'therapeutic',  label: 'Terapêutico',     color: '#5B8DB8' },
  { id: 'spine',        label: 'Para Coluna',     color: '#8B5CF6' },
  { id: 'anxiety',      label: 'Anti-Ansiedade',  color: '#EC8C4C' },
  { id: 'functional',   label: 'Funcional',       color: '#E67E22' },
  { id: 'weightloss',   label: 'Emagrecimento',   color: '#E74C3C' },
  { id: 'elderly',      label: 'Para Idosos',     color: '#16A085' },
  { id: 'postpartum',   label: 'Pós-Parto',       color: '#D45F8E' },
  { id: 'mobility',     label: 'Mobilidade',      color: '#27AE60' },
  { id: 'flexibility',  label: 'Flexibilidade',   color: '#9B59B6' },
  { id: 'breathing',    label: 'Respiratório',    color: '#2980B9' },
  { id: 'preventive',   label: 'Preventivo',      color: '#F39C12' },
]
